### ISSUE TITLE
Prism is brocken as well

### ISSUE THREAD

**Issue by egregors** [vldc-hq/vldc-bot#202]
```
bot_1      | Traceback (most recent call last):
bot_1      |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/utils/promise.py", line 96, in run
bot_1      |     self._result = self.pooled_function(*self.args, **self.kwargs)
bot_1      |   File "/app/bot/mode.py", line 226, in cleanup_wrapper
bot_1      |     return cleanup_inner_wrapper(seconds, remove_cmd, remove_reply, args,
bot_1      |   File "/app/bot/mode.py", line 194, in cleanup_inner_wrapper
bot_1      |     result = func(*args, **kwargs)
bot_1      |   File "/app/bot/skills/prism.py", line 86, in show_top
bot_1      |     words = _eval_filter(default_words, _get_pred(context))
bot_1      |   File "/app/bot/skills/prism.py", line 78, in _eval_filter
bot_1      |     return list(filter(inner_pred, words.copy()))
bot_1      | AttributeError: 'Cursor' object has no attribute 'copy'
```

**Comment by C-Pro** [comment]
Normal'no zhe bylo! With list comprehension

**Comment by egregors** [comment]
@C-Pro Bylo normalno for `/top` with a predicats. But for a call `/top` without agrs `words` becomes a `Curson` instead of `List`

**Comment by C-Pro** [comment]
> @C-Pro Bylo normalno for `/top` with a predicats. But for a call `/top` without agrs `words` becomes a `Curson` instead of `List`

Nu cho ty nachinaesh? Normalno zhe obshalis'
